// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from vbn_ros_msgs:msg/VisionNavigationEstimation.idl
// generated code does not contain a copyright notice

#ifndef VBN_ROS_MSGS__MSG__DETAIL__VISION_NAVIGATION_ESTIMATION__STRUCT_H_
#define VBN_ROS_MSGS__MSG__DETAIL__VISION_NAVIGATION_ESTIMATION__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'NAVIGATION_ESTIMATION_FLAGS_UNKNOWN'.
/**
  * enum VisionNavigationEstimationFlags
  * Default unknown value
 */
enum
{
  vbn_ros_msgs__msg__VisionNavigationEstimation__NAVIGATION_ESTIMATION_FLAGS_UNKNOWN = 0
};

/// Constant 'NAVIGATION_ESTIMATION_FLAGS_OK'.
/**
  * Estimation has valid data
 */
enum
{
  vbn_ros_msgs__msg__VisionNavigationEstimation__NAVIGATION_ESTIMATION_FLAGS_OK = 1
};

/// Constant 'NAVIGATION_ESTIMATION_FLAGS_ABS_OK'.
/**
  * Absolute position estimation is reliable
 */
enum
{
  vbn_ros_msgs__msg__VisionNavigationEstimation__NAVIGATION_ESTIMATION_FLAGS_ABS_OK = 2
};

// Include directives for member types
// Member 'header'
#include "std_msgs/msg/detail/header__struct.h"
// Member 'position'
#include "geographic_msgs/msg/detail/geo_point__struct.h"

/// Struct defined in msg/VisionNavigationEstimation in the package vbn_ros_msgs.
/**
  * Message associated with the MAVLINK msg VISION_NAVIGATION_ESTIMATION (Tekever dialect, custom).
 */
typedef struct vbn_ros_msgs__msg__VisionNavigationEstimation
{
  /// Estimate generated by the VBN system, to be delivered to the autopilot
  std_msgs__msg__Header header;
  geographic_msgs__msg__GeoPoint position;
  /// Flags
  uint8_t flags;
  /// Estimate of the position error in metres
  float pos_error;
} vbn_ros_msgs__msg__VisionNavigationEstimation;

// Struct for a sequence of vbn_ros_msgs__msg__VisionNavigationEstimation.
typedef struct vbn_ros_msgs__msg__VisionNavigationEstimation__Sequence
{
  vbn_ros_msgs__msg__VisionNavigationEstimation * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} vbn_ros_msgs__msg__VisionNavigationEstimation__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // VBN_ROS_MSGS__MSG__DETAIL__VISION_NAVIGATION_ESTIMATION__STRUCT_H_
