navnet_node:
  ros__parameters:

# camara

    camera:
      alpha_calibration: 0.2
      pitch_offset_deg: 27.0
      roll_offset_deg: -4.0
      matrix_k: [896.602173,0.0,1003.954285,0.0,881.922974,451.323334,0.0,0.0,1.0]
      dist_coeffs: [1.771178e00,3.254712e00,4.790912e-03,-3.419381e-03,2.092365e-01,2.054499e00,3.929369e00,1.042681e00]
    

# superpoint e superglue

    models:
      scale_cam: 1.0
      scale_map: 1.0
      superpoint:
        nms_radius: 4     # limite de proximidade entre features (ex:4 pixels)
        keypoint_threshold: 0.05  # o nivel de confiança requerido para um ponto ser considerado feature
        max_keypoints: 1024    # limite de features
      superglue:
        weights: "outdoor"
        sinkhorn_iterations: 70  # numero de interacoes
        match_threshold: 0.9   # percentagem de comfiança no match 0.2 = 20%
  
# pnp e ransac
    
    pnp:
      min_points: 6.0 # numero minimo para deixar o ransac sequer correr (e impossivel ser menos de 4)
      reprojection_error: 5.0   # raio limite em pixeis da reprjecao do ransac
      confidence: 0.99 # correr ransac ate convergir com esta confianca
      interationscount: 2000.0 # ransac max interations